blog/urls.py
from django.urls import path

from . import views

app_name='blog'

urlpatterns = [
    path("",views.all_blogs,name="all_blogs"),
    path("<int:blog_id>/",views.detail,name="detail"),

]

personal_portfolio/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from portfolio import views
from django.conf.urls import include


urlpatterns = [
    path("",views.home,name="home"),
    path("admin/", admin.site.urls),
    path('blog/', include('blog.urls')),
    path('publications/', include('publications.urls')),
]

urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

publications/urls.py
from django.urls import path

from . import views

app_name='publications'

urlpatterns = [
    path("",views.all_publications,name="all_publications"),
    #path("<int:blog_id>/",views.detail,name="detail"),

]

blog/models.py
from django.db import models

# Create your models here.
class Blog(models.Model):
        title=models.CharField(max_length=200)
        description=models.TextField()
        #pdfFile=models.FileField(upload_to="portfolio/files/")
        date=models.DateField()

        def __str__(self):
            return self.title

portfolio/models.py
from django.db import models

# Create your models here.
class Project(models.Model):
    title=models.CharField(max_length=200)
    description=models.CharField(max_length=450)
    image=models.ImageField(upload_to="portfolio/images/")
    url=models.URLField(blank=True)

    def __str__(self):
        return self.title

publications/models.py
from django.db import models


# Create your models here.
class Publication(models.Model):
    title=models.CharField(max_length=450)
    author=models.CharField(max_length=450)
    journal=models.CharField(max_length=300)
    #description=models.CharField(max_length=450)
    image=models.ImageField(upload_to="portfolio/images/")
    url=models.URLField(blank=True)
    date=models.DateField(null=True, blank=True)

    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Blog

# Create your views here.
def all_blogs(request):
    blogs=Blog.objects.order_by('-date')
    return render(request,'blog/all_blogs.html',{'blogs':blogs})

def detail(request,blog_id):
    blog=get_object_or_404(Blog,pk=blog_id)
    return render(request, 'blog/detail.html',{'blog':blog})

portfolio/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Project

# Create your views here.
def home(request):
    projects=Project.objects.all()
    #return HttpResponse("my portfolio page")
    return render(request, 'portfolio/home.html',{'projects':projects})

publications/views.py
from django.shortcuts import render
from .models import Publication

# Create your views here.
def all_publications(request):
    publications=Publication.objects.all()
    return render(request,'publications/all_publications.html',{'publications':publications})

blog/templates/blog/all_blogs.html
{% extends 'portfolio/base.html' %}
{% block content %}


<!--
<h2>Sean has {{blogs.count}} blog{{blogs.count|pluralize}}</h2>
    //-->



{% for blog in blogs %}

<br>
<br>
<a href="{% url 'blog:detail' blog.id %}"><h4 style="color:black;">{{ blog.title }}<h4></a>
<h6>{{blog.date| date:'M d Y'|upper}}</h6>
<p>{{ blog.description|striptags |truncatechars:300 }}</p>


{% endfor %}

{% endblock%}

blog/templates/blog/detail.html
{% extends 'portfolio/base.html' %}
{% block content %}

<br>
<br>
<h1>{{ blog.title }}</h1>
<h4>{{blog.date|date:'F jS Y'}}</h4>
<br>

{{blog.description|safe}}

{% endblock %}

portfolio/templates/portfolio/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

  <link rel="stylesheet" href="{% static "portfolio/custom.css" %}">

  <link href="https://fonts.googleapis.com/css?family=Lato&display=swap" rel="stylesheet">

  <link rel="icon" type="image/png" href="{% static "portfolio/Logo.png" %}">

  <title>Sean O'Sullivan</title>
</head>

<body>

  <nav id="topNav" class="navbar navbar-expand-md navbar-light">
    <div class="container">
      <a class="navbar-brand" href="{% url 'home' %}">
        <img src="{% static "portfolio/Logo.jpg" %}" width="30" height="30" class="d-inline-block align-top" alt="S">
        <span>Sean O'Sullivan</span>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse text-center" id="navbarNav">
          <ul class="navbar-nav ml-auto">
              <li class="nav-item">
                  <a class="nav-link" href="{% static 'portfolio/SeanOSullivan_CV.pdf' %}">CV</a>
              </li>
              <li class="nav-item">
                  <a class="nav-link" href="https://www.linkedin.com/in/sean-james-o-sullivan-m-d-ph-d-ab694034" target="_blank">LinkedIn</a>
              </li>
              <li class="nav-item">
                  <a class="nav-link" href="https://instagram.com/seano1023?igshid=YmMyMTA2M2Y=" target="_blank">Instagram</a>
              </li>
              <li class="nav-item">
                  <a class="nav-link" href="https://www.youtube.com/@seanosullivan4613" target="_blank">YouTube</a>
              </li>
              <li class="nav-item">
                  <a class="nav-link" href="https://www.imdb.com/name/nm4310811/?ref_=ra_gb_ln" target="_blank">IMDB</a>
              </li>
              <li class="nav-item">
                  <a class="nav-link" href="https://www.doximity.com/profiles/d1033608-455a-4cff-9f61-ce5196de2c02/edit" target="_blank">doximity</a>
              </li>
              <li>
                  <a role="button" href="{% url 'blog:all_blogs' %}" class="btn btn-Light">Blog</a>
              </li>
              <li>
                  <a role="button" href="{% url 'publications:all_publications' %}" class="btn btn-Link">Publications</a>
              </li>
          </ul>
      </div>
    </div>
  </nav>
  <div class="container">
    {% block content %}{% endblock %}
  </div>

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>

</html>

portfolio/templates/portfolio/home.html
{% extends 'portfolio/base.html' %}
{% block content %}




<!--
    <a href="{% url 'blog:all_blogs' %}">Blog</a>

    <br>
    {% load static %}

    <a href="{% static 'portfolio/resume.pdf'%}"> Resume</a>
>-->

<div class="row justify-content-center my-3">
    <div class="col-5">
        <img src="{% static 'portfolio/picture1.jpg' %}" width="450" height="550">
    </div>
</div>

<div class="row justify-content-center mb-3">
    <div class="col-md-9 text-center">
        <h1 id="hometext" class="font-weight-bold">Sean J. O'Sullivan, MD, PhD Resident Psychiatrist  </h1>
        <h2 id="hometext">University of Texas at Austin</h2>
    </div>
</div>

<!--
<h2 class="mt-5">Portfolio</h2>
<hr>
<div class="row">
  {% for project in projects %}
  <div class="col-lg-4 col-md-6">

    {% if project.url %}
    <a href="{{ project.url }}">
      <img src="{{ project.image.url }}" class="img-fluid mb-2">
    </a>
    {% else %}

    <img src="{{ project.image.url }}" class="img-fluid mb-2">
    {% endif %}
    <h3>{{ project.title }}</h3>
    <p>{{ project.description }}</p>

  </div>
  {% endfor %}
</div>
    >-->
{% endblock %}

publications/templates/publications/all_publications.html
{% extends 'portfolio/base.html' %}
{% block content %}

<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style>
        * {
            box-sizing: border-box;
        }

        /* Create two equal columns that floats next to each other */
        .column1 {
            float: left;
            width: 15%;
            padding: 10px;
        }

        .column2 {
            float: left;
            width: 85%;
            padding: 10px;
        }

        /* Clear floats after the columns */
        .row:after {
            content: "";
            display: table;
            clear: both;
        }
    </style>
</head>
<body>
    <h1 class="mt-5">Publications </h1>
    <hr>

    {% for publication in publications reversed %}
    <br>
    <br>
    <div class="row">
        <div class="column1">
            <a href="{{ publication.url }}">
                <img src="{{ publication.image.url }}" class="img-fluid mb-2">
            </a>
        </div>
        <div class="column2">
            <a href="{{ publication.url }}"><h4 style="color:black;">{{ publication.title }}<h4></a>
            <h6>{{ publication.journal|striptags |truncatechars:300  }}</h6>
            <h6>{{ publication.author|striptags |truncatechars:300  }}</h6>
            
        </div>
    </div>
    <!--
      height: 300px; /* Should be removed. Only for demonstration */
      height: 300px; /* Should be removed. Only for demonstration */
      <a href="{{ publication.url }}">
      <img src="{{ publication.image.url }}" class="img-fluid mb-2">
      </a>


      <a href="{{ publication.url }}"><h4 style="color:black;">{{ publication.title }}<h4></a>

      <h6>{{ publication.journal|striptags |truncatechars:300  }}</h6>
      <h6>{{ publication.author|striptags |truncatechars:300  }}</h6>
     <h6>{{publication.date| date:'M d Y'|upper}}</h6>
     -->
    {% endfor %}
    <div class="breaker"></div>
    <div class="row">
    </div>





    {% endblock%}
</body>